application/admin/controllers/IntergralGoodsController.php
<?php

namespace admin\controllers;

use app\search\GoodsCouponSearch;
use common\models\IntergralGoodsAttr;
use common\models\IntergralGoodsAttrGroup;
use common\models\GoodsCoupon;
use common\models\IntergralGoodsSku;
use common\models\UploadForm;
use Yii;
use common\models\IntergralGoods;
use common\search\IntergralGoodsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * GoodsController implements the CRUD actions for Goods model.
 */
class IntergralGoodsController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Goods models.
     * @return mixed
     */
    public function actionIndex()
    {
        $request = Yii::$app->request->queryParams;
        $this->checkManager() or $request['IntergralGoodsSearch']['user_id'] = Yii::$app->user->id;
        $request['IntergralGoodsSearch']['isdelete'] = 0;

        $searchModel = new IntergralGoodsSearch();
        $dataProvider = $searchModel->search($request);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Goods model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Goods model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new IntergralGoods();

        if ($model->load(Yii::$app->request->post())) {
            $model->goods_image = json_encode($model->goods_image);
//            $model->third_code = (string)$model->setThirdCode();

            if ($model->save()){
                $sku=json_decode($model->attr);
                $list=array();
                foreach ($sku as $key=>$item){
                    $skumodel=new IntergralGoodsSku();
                    $skumodel->goods_id=$model->id;
                    $skumodel->attr=json_encode($item->attr);
                    $skumodel->num=$item->num;
                    $skumodel->integral=$item->integral;
                    $skumodel->price=$item->price;
                    $skumodel->goods_code=$item->goods_code;
                    $skumodel->picimg=$item->picimg;
                    if ($skumodel->save()){
                        $list[]=$skumodel->attributes;
                    }
                }
                $model->attr=json_encode($list);
                if($model->save()){
                    return $this->redirect(['index']);
                }

            }

        }
        $model->goods_state = 1;
        $model->goods_hot = 0;
        return $this->render('create', [
            'model' => $model,

        ]);
    }


    /**
     *  当前商品的优惠劵列表
     */
    public  function actionCouponList($goodId){

        return $this->redirect(['goods-coupon/index','goodId'=>$goodId]);
    }

    /**
     * Updates an existing Goods model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id,$defaultTitle=0)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->goods_image=json_encode($model->goods_image);
            $model->goods_edittime=date('Y-m-d H:i:s');
            if ($model->save()){
                $sku=json_decode($model->attr,true);

                $list=array();
                $skulist= IntergralGoodsSku::find()->where(['goods_id'=>$model->id])->all();

                if (count($sku)>count($skulist)){
                    foreach ($skulist as $key=>$item){
                        $item->goods_id=$model->id;
                        $item->attr=json_encode($sku[$key]['attr']);
                        $item->num=$sku[$key]['num'];
                        $item->price=$sku[$key]['price'];
                        $item->integral=$sku[$key]['integral'];
                        $item->goods_code=$sku[$key]['goods_code'];
                        $item->picimg=$sku[$key]['picimg'];
                        if ($item->save()){
                            $list[]=$item->attributes;
                        }
                    }
                    for ($i=count($skulist);$i<count($sku);$i++){
                        $skumodel=new IntergralGoodsSku();
                        $skumodel->goods_id=$model->id;
                        $skumodel->attr=json_encode($sku[$i]['attr']);
                        $skumodel->num=$sku[$i]['num'];
                        $skumodel->price=$sku[$i]['price'];
                        $skumodel->integral=$sku[$i]['integral'];
                        $skumodel->goods_code=$sku[$i]['goods_code'];
                        $skumodel->picimg=$sku[$i]['picimg'];
                        if ($skumodel->save()){
                            $list[]=$skumodel->attributes;
                        }
                    }
                }else{
                    foreach ($skulist as $key=>$item){
                        if ($key<count($sku)){
                            $item->goods_id=$model->id;
                            $item->attr=json_encode($sku[$key]['attr']);
                            $item->num=$sku[$key]['num'];
                            $item->price=$sku[$key]['price'];
                            $item->integral=$sku[$key]['integral'];
                            $item->goods_code=$sku[$key]['goods_code'];
                            $item->picimg=$sku[$key]['picimg'];
                            if ($item->save()){
                                $list[]=$item->attributes;
                            }
                        }else{
                            $item->delete();
                        }

                    }
                }

                $model->attr=json_encode($list);
                if($model->save()){
                    return $this->redirect(['index']);
                }

            }else{
                $model->goods_image= json_decode($model->goods_image);
            }

        }


        return $this->render('update', [
            'model' => $model,
            'active'=>'goods',
            'defaultTitle'=>$defaultTitle
        ]);
    }



    /**
     * Deletes an existing Goods model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model =IntergralGoods::findOne(['id'=>$id]);
        $model->isdelete = 1;
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Goods model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Goods the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = IntergralGoods::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionUpgoods(){
        $json=array('code'=>0,'mg'=>'参数错误');
        if (yii::$app->request->isPost){
            $post=yii::$app->request->post();
            $model=IntergralGoods::findOne(['id'=>$post['id']]);
            if (!empty($model)){
                $model->goods_state=1;
                if ($model->save()){
                    $json=array('code'=>1,'mg'=>'上架成功');
                }else{
                    $json=array('code'=>0,'mg'=>'上架失败');
                }
            }else{
                $json=array('code'=>0,'mg'=>'参数错误');
            }
        }

        echo json_encode($json);yii::$app->end();
    }

    public function actionDngoods(){
        $json=array('code'=>0,'mg'=>'参数错误');
        if (yii::$app->request->isPost){
            $post=yii::$app->request->post();
            $model=IntergralGoods::findOne(['id'=>$post['id']]);

            if (!empty($model)){
                $model->goods_state=0;
                if ($model->save()){
                    $json=array('code'=>1,'mg'=>'下架成功');
                }else{
                    $json=array('code'=>0,'mg'=>'下架失败');
                }
            }else{
                $json=array('code'=>0,'mg'=>'参数错误');
            }
        }

        echo json_encode($json);yii::$app->end();
    }

    public function actionUpload(){
        header("Access-Control-Allow-Origin:*");
        $json=array('state'=>0,'error'=>'参数错误');
        if (Yii::$app->request->post()){

            $post=Yii::$app->request->post();

            $uploadedFile = new UploadForm();

            $uploadedFile->file = UploadedFile::getInstanceByName("file");

            if ($uploadedFile->file && $uploadedFile->validate()) {

                $pieces = explode("/",$uploadedFile->file->type);

//                $filename=$uploadedFile->createImagePathWithExtension($uploadedFile->file->extension,'/uploads/goods/');
            $filename=$uploadedFile->createImagePathMD5($uploadedFile->file->extension,'/uploads/goods/',$uploadedFile->file->tempName);
            $uploadedFile->saveImage($uploadedFile->file,$filename);

                $json=array(
                    'code'=>0,
                    'url'=>yii::$app->request->hostInfo.$filename,
                    'attachment'=>$filename
                );

            }

        }else{

application/admin/views/intergral-goods/_form1.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Goods */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="goods-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'goods_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'goods_jingle')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'gc_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'use_attr')->textInput() ?>

    <?= $form->field($model, 'brand_id')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'goods_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'goods_promotion_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'goods_promotion_type')->textInput() ?>

    <?= $form->field($model, 'goods_marketprice')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'goods_serial')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'goods_storage_alarm')->textInput() ?>

    <?= $form->field($model, 'goods_click')->textInput() ?>

    <?= $form->field($model, 'goods_salenum')->textInput() ?>

    <?= $form->field($model, 'goods_collect')->textInput() ?>

    <?= $form->field($model, 'attr')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'goods_spec')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'goods_body')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'mobile_body')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'goods_storage')->textInput() ?>

    <?= $form->field($model, 'goods_image')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'goods_state')->textInput() ?>

    <?= $form->field($model, 'goods_addtime')->textInput() ?>

    <?= $form->field($model, 'goods_edittime')->textInput() ?>

    <?= $form->field($model, 'goods_vat')->textInput() ?>

    <?= $form->field($model, 'goods_commend')->textInput() ?>

    <?= $form->field($model, 'evaluation_good_star')->textInput() ?>

    <?= $form->field($model, 'evaluation_count')->textInput() ?>

    <?= $form->field($model, 'is_virtual')->textInput() ?>

    <?= $form->field($model, 'is_appoint')->textInput() ?>

    <?= $form->field($model, 'is_presell')->textInput() ?>

    <?= $form->field($model, 'have_gift')->textInput() ?>

    <?= $form->field($model, 'isdelete')->textInput() ?>

    <?= $form->field($model, 'type')->textInput() ?>

    <?= $form->field($model, 'integral')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

application/admin/views/intergral-goods/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\search\GoodsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="goods-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'goods_name') ?>

    <?= $form->field($model, 'goods_jingle') ?>

    <?= $form->field($model, 'gc_id') ?>

    <?= $form->field($model, 'use_attr') ?>

    <?php // echo $form->field($model, 'brand_id') ?>

    <?php // echo $form->field($model, 'goods_price') ?>

    <?php // echo $form->field($model, 'goods_promotion_price') ?>

    <?php // echo $form->field($model, 'goods_promotion_type') ?>

    <?php // echo $form->field($model, 'goods_marketprice') ?>

    <?php // echo $form->field($model, 'goods_serial') ?>

    <?php // echo $form->field($model, 'goods_storage_alarm') ?>

    <?php // echo $form->field($model, 'goods_click') ?>

    <?php // echo $form->field($model, 'goods_salenum') ?>

    <?php // echo $form->field($model, 'goods_collect') ?>

    <?php // echo $form->field($model, 'attr') ?>

    <?php // echo $form->field($model, 'goods_spec') ?>

    <?php // echo $form->field($model, 'goods_body') ?>

    <?php // echo $form->field($model, 'mobile_body') ?>

    <?php // echo $form->field($model, 'goods_storage') ?>

    <?php // echo $form->field($model, 'goods_image') ?>

    <?php // echo $form->field($model, 'goods_state') ?>

    <?php // echo $form->field($model, 'goods_addtime') ?>

    <?php // echo $form->field($model, 'goods_edittime') ?>

    <?php // echo $form->field($model, 'goods_vat') ?>

    <?php // echo $form->field($model, 'goods_commend') ?>

    <?php // echo $form->field($model, 'evaluation_good_star') ?>

    <?php // echo $form->field($model, 'evaluation_count') ?>

    <?php // echo $form->field($model, 'is_virtual') ?>

    <?php // echo $form->field($model, 'is_appoint') ?>

    <?php // echo $form->field($model, 'is_presell') ?>

    <?php // echo $form->field($model, 'have_gift') ?>

    <?php // echo $form->field($model, 'isdelete') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'integral') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

application/admin/views/intergral-goods/create.php
<?php

use yii\helpers\Html;
use DL\service\UrlService;

/* @var $this yii\web\View */
/* @var $model common\models\Goods */

$this->title = '发布商品';
$this->params['breadcrumbs'][] = ['label' => '积分商城', 'url' => 'javascript:void(0);'];
$this->params['breadcrumbs'][] = ['label' => '商品列表', 'url' => ['intergral-goods/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel">

    <?= $this->render('_form', [ 'etitle' => $this->title,
        'model' => $model,
    ]) ?>

</div>

application/admin/views/intergral-goods/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\StringHelper;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\search\GoodsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '商品列表';
$this->params['breadcrumbs'][] = ['label' => '积分商城', 'url' => 'javascript:void(0);'];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="panel">
    <div class="panel-heading">
        <span class="panel-title"><?= Html::encode($this->title) ?>
            <span style="float: right;text-align: right;">
        <?= Html::a('发布商品', ['create'], ['class' => 'btn btn-success']) ?>
    </span>

        </span>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>




    <div class="panel-body">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                array(
                    'format' => 'raw',
                    'attribute' => 'goods_image',
                    'label'=>'缩略图',
                    'value'=>function($filterModel){
                        $itm=$filterModel->goods_pic;
                        if ($itm){
                            return Html::img(yii::$app->request->hostInfo.$itm, ['width' =>30]);
                        }else{
                            return '无';
                        }

                    },
                ),
                array(
                    'attribute' => 'goods_name',
                    'label'=>'商品名称',
                    'value'=>function($filterModel){
                        return StringHelper::truncate($filterModel->goods_name, 20);

                    },
                ),
                array(
                    'attribute' => 'id',
                    'label'=>'商品ID',
                ),
                array(
                    'attribute' => 'gc_id',
                    'label'=>'商品分类',
                    'value'=>function($filterModel){
                        return $filterModel->gclass->name;

                    },
                ),
                [
                    'attribute' => 'goods_integral',
                    'label'=>'积分价格',
                ],
//                'goods_click',
//                'goods_salenum',
                array(
                    'format' => 'raw',
                    'attribute' => 'goods_state',
                    'label'=>'状态',
                    'value'=>function($filterModel){

                        switch ($filterModel->goods_state){
                            case 10:
                                return '<span class="label label-danger">商品违规</span>';
                                break;
                            case 0:
                                return '<span class="label">已下架</span> | <button type="button" class="btn  btn-success btn-xs upgoods" data-id="'.$filterModel->id.'">上架</button>';
                                break;
                            case 1:
                                return '<span class="label label-success">已上架</span> | <button type="button" class="btn btn-default btn-xs dngoods" data-id="'.$filterModel->id.'">下架</button>';
                                break;
                        }

                    },
                ),
                [
                    'attribute' => 'goods_hot',
                    'label'=>'积分首页展示',
                    'value' => function ($model) {
                        $dic = [
                            '0' => '不展示',
                            '1' => '展示',
                        ];

                        return isset($dic[$model->goods_hot]) ? $dic[$model->goods_hot] : '-';
                    }
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'header'=>'操作',
                    'template' => ' {update} {delete}',
                    'buttons'=>[
                        'view'=>function($url, $model, $key){
                            $url=yii::$app->request->hostInfo.'/admin.php?r=intergral-goods/view&id='.$model->id ;
                            return  Html::a('查看', $url, ['title' => '查看','data-toggle'=>'modal','class'=>'a_margin'] ) ;
                        },
                        'update' => function ($url, $model, $key) {
                            return  Html::a('更新', $url, ['title' => '更新','data-toggle'=>'modal','class'=>'a_margin'] ) ;
                        },
                        'delete'=> function ($url, $model, $key) {
                            return  Html::a('删除',$url, ['title' => '删除','data-toggle'=>'modal', 'data-id'=>$model->id,'class'=>'a_margin'] ) ;
                        },
                    ],

                ],
            ],
        ]); ?>
    </div>

</div>
<script type="text/javascript">
    var _csrf="<?php echo Yii::$app->getRequest()->getCsrfToken();?>";

    $(document).on("click",'.upgoods',function () {
        var id=$(this).attr('data-id');
        var upbut=this;

        $.post("<?php echo Url::toRoute(['intergral-goods/upgoods']);?>",{_csrf:_csrf,id:id},function (res) {
            if (res.code==1){
                var html='<span class="label label-success">已上架</span> | <button type="button" class="btn btn-default btn-xs dngoods" data-id="'+id+'">下架</button>'
                $(upbut).parent().html(html);
            }else{
                alert(res.mg);
            }
        },'json');

    });

    $(document).on("click",'.dngoods',function () {
        var id=$(this).attr('data-id');
        var dnbut=this;

        $.post("<?php echo Url::toRoute(['intergral-goods/dngoods']);?>",{_csrf:_csrf,id:id},function (res) {
            if (res.code==1){
                var html='<span class="label">已下架</span> | <button type="button" class="btn  btn-success btn-xs upgoods" data-id="'+id+'">上架</button>'
                $(dnbut).parent().html(html);
            }else{
                alert(res.mg);
            }
        },'json');

    });

    $(".fa-bitbucket").click(function(){
        if (confirm("确定要删除该分类么？")) {
            var del=$(this).parent('a');
            var _csrf =$("#_csrf").val();
            $.post("<?php echo Url::toRoute('intergral-goods/delete');?>"+"&id="+del.attr('data-id'),{_csrf:_csrf},function(data){
                if (data.status) {
                    window.location.reload();
                }else{
                    alert(data.msg);
                }

            },'json');
        }
    });
</script>

application/admin/views/intergral-goods/update.php
<?php

use yii\helpers\Html;
use DL\service\UrlService;
/* @var $this yii\web\View */
/* @var $model common\models\Goods */

$this->title =($defaultTitle==0)?'编辑商品':'添加商品';
$this->params['breadcrumbs'][] = ['label' => '积分商城', 'url' => 'javascript:void(0);'];
$this->params['breadcrumbs'][] = ['label' => '商品列表', 'url' => ['intergral-goods/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    .tab_title, .tab_title a {
        margin: 0;
        padding: 0;
        text-align: center;
    }

    .col-lg-2.tab_title.active>a {
        color: #fff!important;
        background-color: #1a7ab9;
    }
</style>
<div class="panel">

    <ul class="nav nav-tabs dl_tab" style="display: none">
        <li class="col-lg-2 tab_title <?=('goods'==$active)?'active':''?>"><a  href="<?=UrlService::build(['goods/update','id'=>$model->id])?>">商品</a></li>
        <li class="col-lg-2 tab_title <?=('coupon'==$active)?'active':''?>"><a  href="<?=UrlService::build(['goods/coupon-list','goodId'=>$model->id])?>">优惠劵</a></li>
    </ul>
    <?= $this->render('_form', [ 'etitle' => $this->title,
        'model' => $model,
    ]) ?>

</div>

application/admin/views/intergral-goods/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Goods */

$this->title = $model->goods_name;
$this->params['breadcrumbs'][] = ['label' => 'Goods', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$statusDic = [
    0 => '下架',
    1 => '正常',
    10 => '违规（禁售）',
];

function formatJsonImg ($jsonString) {
    $imgs = json_decode($jsonString, true);

    $result = '';
    if ($imgs) {
        foreach ($imgs AS $img) {
            $result .= sprintf('<img src="%s" alt="%s" >', $img['imgurl'], '相册');
        }
    }

    return $result;
}
?>
<div class="goods-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
//            'id',
            'goods_name',
            'goods_jingle',
            [
                'attribute' => 'gc_id',
                'label' => '商品分类',
                'value' => $model->gclass->name,
            ],
//            'use_attr',
//            [
//                'attribute' => 'brand_id',
//                'label' => '品牌',
//                'value' => $model->branddata->brand_name,
//            ],
            'goods_price',
            'goods_marketprice',
//            'goods_promotion_price',
//            'goods_promotion_type',
            'goods_serial',
//            'goods_storage_alarm',
            'goods_click',
            'goods_salenum',
            'goods_collect',

//            'goods_spec:ntext',
            [
                'attribute' => 'goods_body',
                'label' => '商品详情	',
                'format' => 'raw',
            ],
//            'mobile_body:ntext',
            'goods_storage',
            [
                'attribute' => 'goods_image',
                'label' => '商品相册',
                'format' => 'raw',
                'value' => formatJsonImg($model->goods_image)
            ],
            [
                'attribute' => 'goods_state',
                'label' => '商品状态	',
                'format' => 'raw',
                'value' => isset($statusDic[$model->goods_state]) ?$statusDic[$model->goods_state]: '-'
            ],
//            'goods_addtime',
//            'goods_edittime',
//            'goods_vat',
//            'goods_commend',
            'evaluation_good_star',
            'evaluation_count',
//            'is_virtual',
//            'is_appoint',
//            'is_presell',
//            'have_gift',
            [
                'attribute' => 'isdelete',
                'label' => '是否删除',
                'value' => (int)$model->isdelete ? '是' : '否'
            ],
            [
                'attribute' => 'type',
                'label' => '商品类型',
                'value' => $model->typeInfo
            ],
            'integral',
        ],
    ]) ?>

</div>