application/wap/controllers/FitupSchoolController.php
<?php


namespace wap\controllers;
use common\models\MemberForm;
use common\models\NavsWap;
use wap\models\Advertising;
use wap\models\FitupAnswer;
use wap\models\FitupAppointment;
use wap\models\FitupAttr;
use wap\models\FitupCase;
use wap\models\FitupProblem;
use wap\models\Member;
use wap\models\MTicketConfig;
use wap\models\News;
use wap\models\Newsclassify;
use wap\models\Ticket;
use wap\models\User;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;


/**
 * AddressController implements the CRUD actions for Address model.
 */
class FitupSchoolController extends BaseController
{

    /**
     * Notes: 装修学堂的首页
     * User: qin
     * Date: 2019/6/12
     * Time: 13:27
     */
    public function  actionIndex($ticketId=0){
        $cityId = $this->getRequestCity();

        $select_menu = 0;
        $session_ticket = Yii::$app->session->get('ticketType');
        if ($session_ticket == 'TICKET'){              //史方写的导航
            $session_ticket_id = Yii::$app->session->get('ticketId');
            $ticketConfig = MTicketConfig::findOne([
                'ticket_id' => $session_ticket_id
            ]);
            $ticketConfig->guiders = decodeJsInputUploadIco($ticketConfig->guiders);
        }else{     //西方的导航
            // 首页菜单
            $homeMenus = NavsWap::find()->where(['provinces_id'=>$cityId,'status'=>1,'type'=>'home'])->limit(5)->orderBy('sort ASC')->all();
            $select_menu = 1;
        }

        $newClass = Newsclassify::find()->andWhere(['fid'=>0])->orderBy("isRdm DESC")->all();

        $problemNum = FitupProblem::find()->andFilterWhere(['is_del' => 0, 'is_show' => 1])->andFilterWhere(['>', 'answer_num', 0])->count();

        $problemStr = FitupProblem::find()->andFilterWhere(['is_del' => 0, 'is_show' => 1])->limit(6)->asArray()->all();
        //装修问题
        $problemStr_list = array_chunk($problemStr, 2);

        $list_ids = Newsclassify::find()->where(['fid'=>1,'isShow'=>1])->all();
        $ids = ArrayHelper::getColumn($list_ids,'id');
        $data=News::find()->andFilterWhere([
            'and',
            ['isShow'=>1],
            ['like','provinces_id',$cityId],
            ['in','cid',$ids]
        ]);
        $paixu='createTime DESC';
        //SORT_DESC  SORT_ASC
        $page = $this->getPagedRows($data, ['order' => $paixu, 'pageSize' => '6', 'rows' => 'models']);

        if (isset($_GET['per-page'])){
            $list=array();
            foreach ($page['models'] as $item){
                $jsonlist['id'] = $item->id;
                $jsonlist['title'] = $item->title;
                $jsonlist['time'] = date('Y-m-d',strtotime($item->createTime));
                $jsonlist['pic'] = empty($item->themeImg)?'/public/wap/images/loading.jpg':$item->themeImg;
                $list[]=$jsonlist;
            }
            $json=array('code'=>1,'pagecount'=>$page['pages']->totalCount,'list'=>$list);

            echo json_encode($json);yii::$app->end();
        }

        //广告位显示
        $fitupAdvertising = Advertising::find()->andWhere(['isShow'=>1,'id'=>11])->one();
        if ($select_menu == 0){
            return $this->render('index',[
                'newClass' => $newClass,
                'problemNum' => $problemNum,
                'problemStr_list' =>$problemStr_list,
                'ticketConfig' =>$ticketConfig,
                'select_menu' =>$select_menu,
                'fitupAdvertising' =>$fitupAdvertising,
                'list' => $page['models'],
                'pages' => $page['pages'],
            ]);
        }else{
            return $this->render('index',[
                'newClass' => $newClass,
                'problemNum' => $problemNum,
                'problemStr_list' =>$problemStr_list,
                'fitupAdvertising' =>$fitupAdvertising,
                'list' => $page['models'],
                'pages' => $page['pages'],
                'home_menus' =>$homeMenus,
                'select_menu' =>$select_menu,
            ]);
        }
    }

    /**
     * 获取当前城市发行票据
     * @author daorli
     * Date: 2019/6/5
     */
    protected function getTicketId()
    {
        $ticket = Ticket::findOne([
            'ca_type' => $this->caType,
            'type' => $this->formType,
            'citys' => $this->getRequestCity(),
            'status' => 1
        ]);

        return $ticket ? $ticket->id : 0;
    }
    /**
     * Notes:判断是否登录
     * User: qin
     * Date: 2019/6/12
     * Time: 18:22
     */
    public  function actionJudgeLogin(){

        if (Yii::$app->user->isGuest){
            $json = array('code'=>1,'msg'=>'请先登录');
        }else{
            $json = array('code'=>0,'msg'=>'已经登录');
        }
        return json_encode($json);
    }
    /**
     * Notes: 装修提问
     * User: qin
     * Date: 2019/6/12
     * Time: 15:04
     */
    public function  actionFitupQuestion(){
        $cityId = $this->getRequestCity();
        //是post保存提交
        if (Yii::$app->request->isPost){
            $post = Yii::$app->request->post();
            $fitProblem = new  FitupProblem();
            $fitProblem->problem = $post['content'];
            $fitProblem->provinces_id = $cityId;
            $fitProblem->member_id = Yii::$app->user->id;
            $fitProblem->answer_num = 0;
            $fitProblem->create_time = date('Y-m-d H:i:s');
            if ($fitProblem->save()){
                $json = array('code'=>1,'msg'=>'提问成功');
            }else{
                $json = array('code'=>0,'msg'=>'提问失败');
            }
            return json_encode($json);
        }

        return $this->render('fitup-question');
    }

    /**
     * Notes: 问答列表
     * User: qin
     * Date: 2019/6/12
     * Time: 15:04
     */
    public function  actionQuestionsList($type = -1){
        $data = FitupProblem::find()->andWhere(['is_show'=>1]);

        if ($type == -1){  //查询所有

        }elseif ($type == 0){       //查询没有回答的
             $data->andWhere(['answer_num'=>0]);
        }elseif ($type == 1){        //查询已经回答的
            $data->andWhere(['>','answer_num',0]);
        }
        $paixu=['sort'=>SORT_DESC,'create_time'=>SORT_DESC];
        //SORT_DESC  SORT_ASC
        $page = $this->getPagedRows($data, ['order' => $paixu, 'pageSize' => '6', 'rows' => 'models']);

        if (isset($_GET['per-page'])){
            $list=array();
            foreach ($page['models'] as $item){
                $member = Member::findOne($item->member_id);
                $jsonlist['id'] = $item->id;
                $jsonlist['title'] = $item->problem;
                $jsonlist['date'] = date('Y-m-d',strtotime($item->create_time));
                $jsonlist['avatar'] = empty($member->avatar)?'/public/wap/images/_temp/img_default_user.jpg':$member->avatar;
                $jsonlist['nickname'] = empty($member->nickname)?'/public/wap/images/_temp/img_default_user.jpg':$member->nickname;
                $jsonlist['num'] = $item->answer_num;
                $list[]=$jsonlist;
            }
            $json=array('code'=>1,'pagecount'=>$page['pages']->totalCount,'list'=>$list,'type' => $type);

            echo json_encode($json);yii::$app->end();
        }

        return $this->render('questions-list',[
            'list' => $page['models'],
            'pages' => $page['pages'],
            'type' => $type
        ]);

    }

    /**
     * Notes: 问答详情
     * param FitupAnswer表的id
     * User: qin
     * Date: 2019/6/12
     * Time: 16:34
     */
    public  function actionQuestionDetail($id = 0){

        $allAnswer = FitupAnswer::find()->andWhere(['problem_id'=>$id])->orderBy('create_time DESC')->all();
        $problem = FitupProblem::findOne($id);
        return $this->render('question-detail',[
            'allAnswer' =>$allAnswer,
            'problem' =>$problem,
            'id'=>$id
        ]);
    }

    /**
     * Notes: 用户回答问题
     * User: qin
     * Date: 2019/6/12
     * Time: 16:52
     * @return string
     */
    public function actionAnswerQuestion($id=0){

        if (Yii::$app->request->isPost){
            $data = Yii::$app->request->post();
            $problem = FitupProblem::findOne($data['id']);
            $fitupAnswer= new  FitupAnswer();
            $fitupAnswer->problem_id= $data['id'];
            $fitupAnswer->member_id= Yii::$app->user->id;
            $fitupAnswer->content= $data['content'];
            $fitupAnswer->create_time= date('Y-m-d H:i:s');
            if ($fitupAnswer->save()){
                $fitupAnswerCount = FitupAnswer::find()->andWhere(['problem_id'=>$data['id']])->count();
                $problem->answer_num =intval($fitupAnswerCount);
                $problem->save();
                $json = array('code'=>1,'msg'=>'回答成功');
            }else{
                $json = array('code'=>0,'msg'=>'回答失败');
            }
            return json_encode($json);
        }
        return $this->render('fitup-answer',[
            'id'=>$id]);
    }

    /**
     * Notes:装修详情
     * User: qin
     * Date: 2019/6/13
     * Time: 9:12
     */
    public function  actionFitupCaseDetail($id){

        $fitupCase = FitupCase::findOne($id);

        $user = User::findOne($fitupCase->user_id);

        $cont= json_decode($fitupCase->tab_text);

        return $this->render('fitup-case-detail',[
            'fitupCase'=>$fitupCase,
            'cont'=>$cont,
            'user'=>$user
        ]);

    }

    /**
     * Notes: 装修预约
     * User: qin
     * Date: 2019/6/13
     * Time: 11:32
     */
    public function actionFitupAppointment(){

        if (Yii::$app->request->isPost){
            $data = Yii::$app->request->post();
            $smsdata=yii::$app->session->get('SMS_CODE');
            if (!empty($smsdata)) {
                $smsdataStr = $data['mobile'] . '-' . $data['smscode'];
                if ($smsdata['value_str'] == $smsdataStr) {
                    $fitupAppoint = new  FitupAppointment();
                    $fitupAppoint->member_id = Yii::$app->user->id;

application/wap/views/fitup-school/fitup-answer.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/12
 * Time: 15:05
 */
use yii\helpers\Url;
?>
<div class="head">
    <a href="javascript:history.back(-1)"><img src="/public/wap/images/icon_left.png" alt="返回"></a>
    <h2>我要回答</h2>
</div>
<div class="fitup_ask">
    <form action="">
        <textarea class="textarea" placeholder="请输入您要回复的内容"></textarea>
        <a href="javascript:void(0)" class="btn btn_big">提交信息</a>
    </form>
</div>
<!-- 模态框- 文本提醒-简易版 弹框 -->
<div class="modal modal_explain modal_explain_sm fade" id="myModalExplain2">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <p class="p_title">提交成功</p>
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body">
                <p class="text-align">您已成功提交回复，感谢您的参与！</p>
            </div>
            <!-- 模态框底部 -->
            <div class="modal-footer">
                <a href="<?=Url::toRoute(['fitup-school/question-detail','id'=>$id])?>" class="btn" >确 定</a>
            </div>
        </div>
    </div>
</div>

<div class="modal modal_explain modal_explain_sm modal_remind fade" id="myModalRemind">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <p class="p_title">提醒</p>
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body">
                <p class="text-align" id="tipInfo"></p>
            </div>
            <!-- 模态框底部 -->
            <div class="modal-footer">
                <a href="javascript:void(0)" class="btn" data-dismiss="modal">确 定</a>
            </div>
        </div>
    </div>
</div>


    <script>
        //点击提交
        $(".btn_big").on('click',function () {
            var content = $(".textarea").val();
            var id = '<?=$id?>';

            if(content.length == 0){

                $("#myModalRemind").modal('show');
                $("#tipInfo").text('内容不能为空');
                return ;
            }
            var url = "<?=Url::toRoute(['fitup-school/answer-question'])?>";
            $.post(url,{content:content,id:id},function (res) {
                if (res.code == 1){
                    $("#myModalExplain2").modal('show');
                }else {
                    $("#myModalRemind").modal('show');
                    $("#tipInfo").text('提交失败');
                }
            },'json')
        })
    </script>

application/wap/views/fitup-school/index.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/12
 * Time: 13:30
 */
$this->title = '装修学堂';
$this->params['breadcrumbs'][] = $this->title;

use  yii\helpers\Url;

?>
<link rel="stylesheet" href="<?php echo Yii::$app->request->hostInfo; ?>/public/css/dropload.css">
<script src="<?php echo Yii::$app->request->hostInfo; ?>/public/js/dropload.js"></script>
<div class="head">
    <h2>装修学堂</h2>
</div>
<div class="topNav swiper-container swiper-container-horizontal swiper-container-free-mode">
    <div class="swiper-wrapper com_tab2">
        <a href="<?= Url::toRoute(['fitup-school/fitup-case']) ?>" class="swiper-slide"><img
                    src="/public/wap/images/_temp/img_type11.png"><span>装修案例</span></a>
        <?php foreach ($newClass as $k => $v): ?>
            <a href="<?= Url::toRoute(['news/fitup-news-list', 'fid' => $v->id]) ?>" class="swiper-slide"><img
                        src="<?= $v->icoImg ?>"><span><?= $v->name ?></span></a>
        <?php endforeach; ?>
    </div>
</div>
<div class="fitupschool_ask">
    <div class="com_title">
        <div class="com_title_con">
            <a href="javascript:void(0)" style="width: 50%;">累计解决<span><?= $problemNum ?></span>例用户提问</a>
            <span class="s_title">装修问答</span>
        </div>
    </div>
    <div class="slider carousel slide" data-ride="carousel">
        <!-- 指示符 -->
        <ul class="carousel-indicators" style="display: none;">
            <li data-target="#slider" data-slide-to="0" class="active"></li>
            <li data-target="#slider" data-slide-to="1"></li>
            <li data-target="#slider" data-slide-to="2"></li>
        </ul>
        <!-- 轮播图片 -->
        <div class="carousel-inner">
          <?php foreach ($problemStr_list as $klist=>$vlist):?>
            <ul class="list-unstyled fitupschool_ask_ul carousel-item <?=($klist == 0)?'active':''?>">
                <?php foreach ($vlist as $k=>$item):?>
                <li><a href="<?=Url::toRoute(['fitup-school/question-detail','id'=>$item['id']])?>" class="text-truncate"><?=$item['problem']?></a></li>
                <?php endforeach;?>
            </ul>
          <?php endforeach;?>
        </div>
        <!-- 左右翻页不需要但是删除会报错 -->
        <a id="carleft" class="left carousel-control" href="#slider" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a id="carright" class="right carousel-control" href="#slider" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="fitupschool_ask_btns">
        <a href="javascript:void(0)" id="myQuestion" class="btn"><img src="/public/wap/images/icon_fitup_ask.png" alt="我要提问">我要提问</a>
        <a href="<?=Url::toRoute(['fitup-school/questions-list'])?>" class="btn btn-outline"><img src="/public/wap/images/icon_fitup_answer.png"
                                                                 alt="我要回答">我要回答</a>
    </div>
</div>

<div class="com_ad">
    <a href="<?= $fitupAdvertising ? $fitupAdvertising->url : ''; ?>"><img src="<?= $fitupAdvertising ? $fitupAdvertising->picture : ''; ?>" alt=""></a>
</div>

<!-- 和家资讯 -->
<div class="index_news">
    <div class="index_news_list">

    </div>
</div>

<!-- 菜单是5个，需要加menu_5.四个则不加 -->

<?php if ($select_menu == 0):?>
    <?php include __DIR__ . '/common/footer_sf.php'; ?>
<?php else:?>

    <?php include __DIR__ . '/common/footer_xf.php'; ?>
<?php  endif;?>


<!-- 模态框- 提醒弹框-3s自动消失 -->
<div class="modal modal_explain modal_explain_sm modal_remind fade" id="myModalRemind">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <p class="p_title">提醒</p>
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body">
                <p class="text-align" id="tipInfo"></p>
            </div>
            <!-- 模态框底部 -->
            <div class="modal-footer">
                <a href="javascript:void(0)" class="btn" data-dismiss="modal">确 定</a>
            </div>
        </div>
    </div>
</div>
<!-- tab左右滑动 -->

<script type="text/javascript">

    // 页数
    var page = 0;
    // 每页展示5个
    var size = 10;
    var sum = '<?php echo $pages->totalCount;?>';
    var p = Math.ceil(sum / size);
    var result = '';
    $('.index_news').dropload({
        scrollArea: window,
        distance: 10,
        loadDownFn: function (me) {
            if (page < p) {
                page++;
                // 拼接HTML
                result = '';
                $.get('<?php echo Url::toRoute(["fitup-school/index"]);?>', {
                    page: page,
                    'per-page': size
                }, function (data) {
                    $.each(data.list, function (key, val) {
                        var url = "<?=Url::to(['news/news-detail','id'=>''])?>" + val.id;
                        result += '<a href="'+url+'" class="inl_con">\n' +
                            '            <img src="'+val.pic+'" class="img loading_img"\n' +
                            '                 data-url="'+val.pic+'">\n' +
                            '            <div class="con">\n' +
                            '                <p class="p_name ellipsis">'+val.title+'</p>\n' +
                            '                <p class="p_time"><span class="s1">会展资讯</span><span class="s2">'+val.time+'</span></p>\n' +
                            '            </div>\n' +
                            '        </a>';
                    });
                    $('.index_news_list').append(result);
                    // 每次数据插入，必须重置
                    me.resetload();
                }, 'json');
            } else {

                // 锁定
                me.lock();
                // 无数据
                me.noData();
                // 为了测试，延迟1秒加载
                // 插入数据到页面，放到最后面
                $('.infolist').append(result);

                //settime();
                // 每次数据插入，必须重置
                me.resetload();

            }
        }
    });

    var mySwiper = new Swiper('.topNav', {
        freeMode: true,
        preventClicks: false,//默认true
        freeModeMomentumRatio: 0.5,
        slidesPerView: 'auto',
    });

    $("#myQuestion").on('click',function () {

        var  urlToQuestion = "<?=Url::toRoute(['fitup-school/fitup-question'])?>";
        var  url = "<?=Url::toRoute(['fitup-school/judge-login'])?>";
        $.get(url,function (res) {
            if (res.code==1){
                $("#myModalRemind").modal('show');
                $("#tipInfo").text(res.msg);
            }else {
                window.location.href=urlToQuestion
            }
        },'json');

    })

    $(function () {
        // 获取手指在轮播图元素上的一个滑动方向（左右）
        // 获取界面上轮播图容器
        var $carousels = $('.carousel');
        var startX,endX;
        // 在滑动的一定范围内，才切换图片
        var offset = 50;
        // 注册滑动事件
        $carousels.on('touchstart',function (e) {
            // 手指触摸开始时记录一下手指所在的坐标x
            startX = e.originalEvent.touches[0].clientX;

        });
        $carousels.on('touchmove',function (e) {
            // 目的是：记录手指离开屏幕一瞬间的位置 ，用move事件重复赋值
            endX = e.originalEvent.touches[0].clientX;
        });
        $carousels.on('touchend',function (e) {
            //console.log(endX);
            //结束触摸一瞬间记录手指最后所在坐标x的位置 endX
            //比较endX与startX的大小，并获取每次运动的距离，当距离大于一定值时认为是有方向的变化
            var distance = Math.abs(startX - endX);
            if (distance > offset){
                //说明有方向的变化
                //根据获得的方向 判断是上一张还是下一张出现
                $(this).carousel(startX >endX ? 'next':'prev');
            }
        })
    });
</script>

application/wap/views/fitup-school/question-detail.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/12
 * Time: 16:35
 */
use yii\helpers\Url;
?>

<div class="head">
    <a href="<?=Url::toRoute(['fitup-school/questions-list'])?>"><img src="/public/wap/images/icon_left.png" alt="返回"></a>
    <h2>装修问答</h2>
</div>
<div class="fitupask_list">
    <div class="fitupask_list_con">
        <p class="p_title ellipsis"><em>Q</em><?=$problem->problem?></p>
        <div class="d_user">
            <img src="<?=$problem->member->avatar?>">
            <span class="s_right float-right"><span class="orange"><?=$problem->answer_num?></span>回答</span>
            <p class="p1"><?=$problem->member->nickname?></p>
            <p class="p2"><?=date('Y-m-d',strtotime($problem->answer_num))?></p>
        </div>
    </div>
    <div class="fitupask_list_con">
        <?php foreach ($allAnswer as $k=>$item):?>
            <div class="d_user">
                <img src="<?=($item->member->avatar)?$item->member->avatar:'/public/wap/images/user_head.jpg'?>">
                <span class="s_right float-right mt-0"><?=date('Y-m-d',strtotime($item->create_time))?></span>
                <p class="p1"><?=$item->member->nickname?></p>
                <p class="p2"><?=$item->content?></p>
            </div>
        <?php endforeach;?>
    </div>
</div>
<div class="product_btn">
    <a href="javascript:void(0)" class="btn btn_big">我要回答</a>
</div>

<!-- 模态框- 提醒弹框-3s自动消失 -->
<div class="modal modal_explain modal_explain_sm modal_remind fade" id="myModalRemind">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <p class="p_title">提醒</p>
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body">
                <p class="text-align" id="tipInfo"></p>
            </div>
            <!-- 模态框底部 -->
            <div class="modal-footer">
                <a href="javascript:void(0)" class="btn" data-dismiss="modal">确 定</a>
            </div>
        </div>
    </div>
</div>

<script>

    //点击回答
    $(".btn_big").on('click',function () {

        var urlto = "<?=Url::toRoute(['fitup-school/answer-question','id'=>$id])?>";
        var  url = "<?=Url::toRoute(['fitup-school/judge-login'])?>";
        $.get(url,function (res) {
            if (res.code == 1){
                $("#myModalRemind").modal('show');
                $("#tipInfo").text(res.msg)
            } else {
                window.location.href=urlto;
            }
        },'json');
    })

</script>

application/wap/views/fitup-school/questions-list.php
<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/12
 * Time: 15:14
 */

use yii\helpers\Url;

?>
<link rel="stylesheet" href="<?php echo Yii::$app->request->hostInfo; ?>/public/css/dropload.css">
<script src="<?php echo Yii::$app->request->hostInfo; ?>/public/js/dropload.js"></script>
<div class="head">
    <a href="<?=Url::toRoute(['fitup-school/index'])?>"><img src="/public/wap/images/icon_left.png" alt="返回"></a>
    <h2>装修问答</h2>
</div>
<div class="fitupask_tab">
    <a href="<?=Url::toRoute(['fitup-school/questions-list','type'=>-1])?>" class="<?=($type == -1)?'active':''?>"><span>所有问题</span></a>
    <a href="<?=Url::toRoute(['fitup-school/questions-list','type'=>1])?>" class="<?=($type == 1)?'active':''?>"><span>已回答</span></a>
    <a href="<?=Url::toRoute(['fitup-school/questions-list','type'=>0])?>" class="<?=($type == 0)?'active':''?>"><span>待回答</span></a>
</div>
<div class="fitupask_list">
    <div class="fitupask_ajax">

    </div>
</div>

<script>
    // 页数
    var page = 0;
    // 每页展示5个
    var size = 10;
    var sum = '<?php echo $pages->totalCount;?>';
    var p = Math.ceil(sum / size);
    var result = '';
    var type = '<?=$type?>';
    $('.fitupask_list').dropload({
        scrollArea: window,
        distance: 10,
        loadDownFn: function (me) {
            if (page < p) {
                page++;
                // 拼接HTML
                result = '';
                $.get('<?php echo Url::toRoute(["fitup-school/questions-list"]);?>', {
                    page: page,
                    'per-page': size,
                    type:type
                }, function (data) {
                    $.each(data.list, function (key, val) {console.log(val)
                        var url = "<?=Url::to(['fitup-school/question-detail','id'=>''])?>" + val.id;
                        result += '<a href="'+url+'" class="fitupask_list_con">\n' +
                            '        <p class="p_title ellipsis"><em>Q</em>'+val.title+'</p>\n' +
                            '        <div class="d_user">\n' +
                            '            <img src="'+ (val.avatar == null ? '/public/wap/images/user_head.jpg' : val.avatar)+'">\n' +
                            '            <span class="s_right float-right"><span class="orange">'+val.num+'</span>回答</span>\n' +
                            '            <p class="p1">'+val.nickname+'</p>\n' +
                            '            <p class="p2">'+val.date+'</p>\n' +
                            '        </div>\n' +
                            '    </a>';
                    });
                    $('.fitupask_ajax').append(result);
                    // 每次数据插入，必须重置
                    me.resetload();
                }, 'json');
            } else {

                // 锁定
                me.lock();
                // 无数据
                me.noData();
                // 为了测试，延迟1秒加载
                // 插入数据到页面，放到最后面
                $('.infolist').append(result);
                //settime();
                // 每次数据插入，必须重置
                me.resetload();
            }
        }
    });

</script>