application/index/controllers/PersonalController.php
<?php

namespace index\controllers;

use chenkby\region\RegionAction;
use common\models\Address;
use common\models\AddressMember;
use common\models\Cart;
use common\models\Collect;
use common\models\Comment;
use common\models\Goods;
use common\models\History;
use common\models\IntergralOrder;
use common\models\IntergralOrderGoods;
use common\models\Member;
use common\models\MemberStoreCoupon;
use common\models\Order;
use common\models\OrderGoods;
use common\models\Payment;
use common\models\Provinces;
use common\models\StoreInfo;
use common\models\Ticket;
use common\models\TicketApplyGoods;
use common\models\IntegralLog;
use common\models\UploadForm;
use common\models\User;
use common\search\IntergralGoodsSearch;
use common\search\IntergralOrderSearch;
use DL\vendor\ConfigService;
use DL\vendor\Page;
use DL\WechatRefund;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

class PersonalController extends BaseController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']    //验证是否登录
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    $login = 'Location:' . Yii::$app->request->hostInfo.'/index.php?r=member/login';
                    header($login);
                },
            ],
        ];
    }

    public function actions()
    {
        $actions = parent::actions();
        $actions['get-region'] = [
            'class' => RegionAction::className(),
            'model' => Provinces::className()
        ];
        return $actions;
    }

    /**
     * @return string|void
     *  用户信息
     */
    public function actionIndex()
    {

        $model = Member::findOne(['id' => $this->memberInfo->id]);

        if (Yii::$app->request->isPost) {
            $data = Yii::$app->request->post();
            ($data['avatar']) ? $model->avatar = $data['avatar'] : '';
            ($data['avatarTm']) ? $model->avatarTm = $data['avatarTm'] : '';
            if (isset($data['name'])) {
                $model->nickname = $data['name'];
                $model->wxnick = $data['name'];
            }
            ($data['sex']) ? $model->sex = $data['sex'] : '';
//            $model->sex = 1;
            $bir = $data['year'] . '-' . $data['moth'] . '-' . $data['day'];
            $model->birthday_year = $bir;
            $model->save();
        }

        $this->render('index', [
            'model' => $model,
            'pageIndexKey' => 5
        ]);
    }

    /**
     * @return string|void
     * 积分订单
     */
    public function actionIntegralOrder()
    {
        $model = Member::findOne(['id' => $this->memberInfo->id]);
        $data=Yii::$app->request->get();
        $orderNum=isset($data['orderid'])?$data['orderid']:'';

        $near_time=isset($data['near_time'])?$data['near_time']:'';
        $order_status=isset($data['order_status'])?$data['order_status']:'';

        $query=IntergralOrder::find()->andFilterWhere([
            'buyer_id'=>$model->id,
            'order_state'=>$order_status,
        ])->andFilterWhere(['like','orderid',$orderNum]);

        switch ($near_time){
            case 'all':
                break;
            case  'week':
                $time= date("Y-m-d H:i:s", strtotime("-1 week"));
                $query->andFilterWhere(['>','add_time',$time]);
                break;
            case 'month':
                $time= date("Y-m-d H:i:s", strtotime("-1 month"));
                $query->andFilterWhere(['>','add_time',$time]);
                break;
            case 'threeMonth':
                $time= date("Y-m-d H:i:s", strtotime("-3 month"));
                $query->andFilterWhere(['>','add_time',$time]);
                break;
        }


        $amount=$query->count();
        $page = \Yii::$app->request->get('p', 1);
        $limit = 10;
        $orders = $query->offset(($page-1)* $limit)->orderBy('add_time DESC')->limit($limit)->all();
        $page = new Page($amount, $limit);
        $pageHtml = $page->show();


        return $this->render('integral-order', [
            'model' => $model,
            'orders' => $orders,
            'page' => $page,
            'pageHtml'=>$pageHtml,
            'pageIndexKey' => 1
        ]);
    }

    public function actionReceivedIntergral($number)
    {
        $order = IntergralOrder::findOne([
            'orderid' => $number,
            'order_state' => IntergralOrder::STATUS_WAIT_RECIVE
        ]);

        $order or apiSendError("未找到该订单信息");
        $order->order_state = IntergralOrder::STATUS_FINISH;
        $order->save() and apiSendSuccess();

        apiSendError("确认收货失败");
    }

    /**
     * @return string|void
     * 积分订单 详情
     */
    public function actionIntegralOrderDetail()
    {
        $data=Yii::$app->request->get();
        $model = Member::findOne(['id' => $this->memberInfo->id]);
        $intergralOrder=IntergralOrder::find()->andFilterWhere(['orderid'=>$data['number']])->one();
        $intergralOrderGood=IntergralOrderGoods::find()->andFilterWhere(['order_id'=>$data['number']])->all();

        return $this->render('integral-order-detail', [
            'model' => $model,
            'intergralOrder'=>$intergralOrder,
            'intergralOrderGood'=>$intergralOrderGood
            ]);
    }

    /**
     * @return string|void
     * 积分订单取消
     */
    public function actionIntegralOrderCancel()
    {
        $json=array('code'=>0,'msg'=>'错误提示');
        $data=Yii::$app->request->get();
        $intergralOrder=IntergralOrder::find()->andFilterWhere(['orderid'=>$data['number']])->one();
        if (!empty($intergralOrder)){
            $intergralOrder->order_state=IntergralOrder::STATUS_CLOSE;
            $intergralOrder->save();
            $json=array('code'=>1,'msg'=>'取消成功');
        }
        return json_encode($json);
    }


    /**
     * 优惠劵核销订单
     */
    public  function actionCouponVerifitionOrder(){

        $data=Yii::$app->request->get();
        $model = Member::findOne(['id' => $this->memberInfo->id]);
        $orderNum=isset($data['orderid'])?$data['orderid']:'';

        $near_time=isset($data['near_time'])?$data['near_time']:'';
        $order_status=isset($data['order_status'])?$data['order_status']:'';

        $query=Order::find()->andFilterWhere([
            'buyer_id'=>$this->memberInfo->id,
            'type' => Order::STORE_TYPE_COUPON,
            'order_state'=>$order_status,
        ])->andFilterWhere(['like','orderid',$orderNum]);

        switch ($near_time) {
            case 'all':
                break;
            case  'week':
                $time= date("Y-m-d H:i:s", strtotime("-1 week"));
                $query->andFilterWhere(['>','add_time',$time]);
                break;
            case 'month':
                $time= date("Y-m-d H:i:s", strtotime("-1 month"));
                $query->andFilterWhere(['>','add_time',$time]);
                break;
            case 'threeMonth':
                $time= date("Y-m-d H:i:s", strtotime("-3 month"));
                $query->andFilterWhere(['>','add_time',$time]);
                break;
        }

        $amount=$query->count();
        $page = \Yii::$app->request->get('p', 1);
        $limit = 10;
        $order = $query->offset(($page-1)* $limit)->orderBy('add_time DESC')->limit($limit)->all();
        $page = new Page($amount, $limit);
        $pageHtml = $page->show();

        return $this->render('coupon-verifition-order',
        [
            'order'=>$order,
            'pageHtml'=>$pageHtml,
            'model'=>$model,
            'pageIndexKey' => 11
        ]);
    }
    /**
     * @return string|void
     * 积分订单 详情
     */
    public function actionIntegralOrderDetail2()
    {
        $model = Member::findOne(['id' => $this->memberInfo->id]);
        return $this->render('integral-order-detail2',
            ['model' => $model]);
    }


    /**
     * @return string|void
     * 订单 评价
     */
    public function actionOrderComment($orderId)
    {
        $model = Member::findOne(['id' => $this->memberInfo->id]);
        $order=Order::findOne(['orderid'=>$orderId]);
        return $this->render('order-evaluate', ['model' => $model,'order'=>$order]);
    }

    /**
     * @return string|void
     * 积分订单  物流详情
     */
    public function actionIntegralOrderLogistics()
    {
        $model = Member::findOne(['id' => $this->memberInfo->id]);
        return $this->render('integral-order-logistics', ['model' => $model]);
    }

    /**
     *  我的地址
     */
    public function actionMyAddress($addressId=0)
    {
        $model = Member::findOne(['id' => $this->memberInfo->id]);
        $alladdress = AddressMember::findAll(['memberId' => $this->memberInfo->id]);
        if ($addressId==0){
            $address = new AddressMember();
        }else{
            $address =AddressMember::findOne($addressId);
        }
        if ($address->load(Yii::$app->request->post()) && $address->validate()) {

            $address->memberId = $this->memberInfo->id;
            if ($address->isDefault == 1) {
                Address::updateAll(['isDefault' => 0], ['memberId' => $this->memberInfo->id]);
            }
            if ($address->save()) {
                return $this->redirect(['personal/my-address']);
            }
        }

        return $this->render('my-address', [
            'model' => $model, 'address' => $address, 'alladdress' => $alladdress,
            'pageIndexKey' => 4
            ]);
    }




    /**
     * 删除地址
     */
    public function actionDeleteAddress($id)
    {
        $json = array('code' => 0, 'msg' => '删除失败');
        $is_delete = Address::deleteAll(['id' => $id]);
        if ($is_delete > 0) {
            $json = array('code' => 1, 'msg' => '删除成功');
        }

application/index/views/personal/integral-order-detail.php
<?php
use DL\service\UrlService;
use common\models\FloorIndex;
use common\models\Ticket;
use common\models\IntergralOrder;
include APP_PATH . '/views/common/header.php'; ?>

<?php include APP_PATH . '/views/common/guider.php'; ?>


	<div class="mx-auto w1200 clearfix pb-5 mt-3">
        <?php include __DIR__.'/common/left-column.php' ?>
		<div class="user_content float-right">
			<p class="case_title"><span class="green">全部订单</span></p>
			<div class="casedetail">
							<div class="casedetail_flow">								
								<ul class="list-unstyled cdf_right">
									<li class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_PAY)?'active':'grays'?>">
										<p class="p1">拍下商品</p>
										<span>1</span>

									</li>
									<li class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_SEND)?'active_line':'state_line'?>">
									</li>
									<li class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_SEND)?'active':'grays'?>">
										<p class="p1">付款成功</p>
										<span>2</span>
									</li>
									<li class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_SEND)?'active_line':'state_line'?>">
									</li>
									<li class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_RECIVE)?'active':'grays'?>">
										<p class="p1">卖家发货</p>
										<span>3</span>

									</li>
									<li class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_RECIVE)?'active_line':'state_line'?>">
									</li>
									<li class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_JUDGE)?'active':'grays'?>">
										<p class="p1">确认收货</p>
										<span>4</span>
									</li>
									<li style="display: none" class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_WAIT_JUDGE)?'active_line':'state_line'?>">
									</li>
									<li style="display: none" class="<?=($intergralOrder->order_state >= IntergralOrder::STATUS_CLOSE)?'active':'grays'?>">
										<p class="p1">立即评价</p>
										<span>5</span>
									</li>
								</ul>
							</div>
							<div class="case_detail_c">
								<div class="case_detai_c_tit">订单信息</div>
								<div class="case_detail_c_main">
									<div class="case_detail_l" style="border-right: 1px solid #BADE6E;">
										<div class="case_detail_l_li">
											<span>收货地址：</span>
											<div class="case_detail_l_li_main"><?=$intergralOrder->receiver_address?></div>
										</div>
										<div class="case_detail_l_li">
											<span>买家留言：</span>
											<div class="case_detail_l_li_main">轻拿轻放</div>
										</div>
										<div class="case_detail_l_li">
											<span>订单编号：</span>
											<div class="case_detail_l_li_main"><?=$intergralOrder->orderid?></div>
										</div>
									</div>
									<div class="case_detail_r" style="border-left: none">
										<div class="case_detail_r_li">
											<span>订单状态：</span>
											<div class="case_detail_r_li_main"><?=$intergralOrder->orderState?></div>
										</div>
										<div class="case_detail_r_li">
											<p style="display: none">您可以<a href="javascript:void(0)">申请退款</a></p>
										</div>
										
									</div>
								</div>
							</div>
							<div class="casedetail_con">
								<table class="table mycase_list_table order_detail_title">
									<thead>
										<tr>
											<th class="td1">商品</th>
											<th class="td2">单价</th>
											<th class="td3">数量</th>
											<th class="td8">状态</th>
										</tr>
									</thead>
								</table>
								<table class="table mycase_list_table">
									<tbody>
										<tr class="tr_id">
											<td colspan="9"><span><?=$intergralOrder->add_time?></span>订单号：<?=$intergralOrder->orderid?></td>
										</tr>
                                        <?php foreach ($intergralOrderGood as $orderGood_k=>$orderGood_v):?>
                                            <tr>
                                                <td class="td1">
                                                    <a href="<?=UrlService::build(['intergral-goods/detail','id'=>$orderGood_v->goods_id])?>" class="media">
                                                        <img src="<?=$orderGood_v->goods_pic?>" class="align-self-center"
                                                             style="width:80px">
                                                        <div class="media-body mt-1">
                                                            <h4><?=$orderGood_v->goods_name?></h4>
                                                            <p><?=$orderGood_v->attr?></p>
                                                        </div>
                                                    </a>
                                                </td>
                                                <td class="td2"><span><?=intval($orderGood_v->goods_price)?></span></td>
                                                <td class="td3">× <?=$orderGood_v->goods_num?></td>
                                                <td class="td8" rowspan="2"><?=$intergralOrder->orderState?></td>
                                            </tr>
                                        <?php endforeach;?>
									</tbody>
								</table>					
								<div class="order_detail_bot">					
									<dl>
										<dd class="dd"><span><?=intval($intergralOrder->order_amount)?></span>积分</dd>
										<dt>实付款：</dt>
									</dl>
								</div>
							</div>
						</div>
			

		</div>
		
	</div>

<?php include APP_PATH . '/views/common/footer.php';?>

application/index/views/personal/integral-order-logistics.php
<?php

use DL\service\UrlService;
use common\models\FloorIndex;
use common\models\Ticket;

include APP_PATH . '/views/common/header.php'; ?>

<?php include APP_PATH . '/views/common/guider.php'; ?>


<div class="mx-auto w1200 clearfix pb-5 mt-3">
    <?php include __DIR__ . '/common/left-column.php' ?>
    <div class="user_content float-right">
        <p class="case_title"><span class="green">全部订单</span></p>
        <div class="wuliu_top">
            <div class="wuliu_top_li">
                <ul class="list-unstyled">
                    <li>运单号码：<span>75115748563547895</span></li>
                    <li>物流公司：<span>中通快递</span></li>
                    <li>客服电话：<span>95311</span></li>
                </ul>
            </div>
            <div class="wuliu_top_li">
                <ul class="list-unstyled">
                    <li>收货地址：<span>河南省洛阳市洛龙区</span><span>000000</span><span>张三</span><span>15900000005</span></li>
                </ul>
            </div>
        </div>
        <div class="wuliu_main">
            <div class="wuliu_main_top">已签收</div>
            <div class="wuliu_main_lists">
                <div class="wuliu_main_list1"><span></span>2019-01-01 12:00:00 您已在政和国际四楼中细软完成签收</div>
                <div class="wuliu_main_list"><span></span>2019-01-01 12:00:00 [洛阳市]快件已到达洛阳快递员正在派送中</div>
                <div class="wuliu_main_list"><span></span>2019-01-01 12:00:00 [洛阳市]快件已到达洛阳快递员正在派送中</div>
                <div class="wuliu_main_list"><span></span>2019-01-01 12:00:00 [洛阳市]快件已到达洛阳快递员正在派送中</div>
                <div class="wuliu_main_list"><span></span>2019-01-01 12:00:00 [洛阳市]快件已到达洛阳快递员正在派送中</div>
                <div class="wuliu_main_list"><span></span>2019-01-01 12:00:00 [洛阳市]快件已到达洛阳快递员正在派送中</div>
                <div class="wuliu_main_list"><span></span>2019-01-01 12:00:00 包裹正在等待揽件</div>
            </div>

        </div>


    </div>

</div>

<?php include APP_PATH . '/views/common/footer.php'; ?>

  

application/index/views/personal/integral-order.php
<?php

use DL\service\UrlService;
use common\models\FloorIndex;
use common\models\Ticket;
use \common\models\IntergralOrder;

include APP_PATH . '/views/common/header.php'; ?>

<?php include APP_PATH . '/views/common/guider.php'; ?>

<div class="mx-auto w1200 clearfix pb-5 mt-3">
    <?php include __DIR__.'/common/left-column.php' ?>
    <script>
        $(function () {
            <?php
            if ($_GET) {
                echo 'var obj=' . json_encode($_GET) . ';';
            }
            ?>
            if (typeof(obj) != 'undefined') {
                for(k in obj){
                    if (k=='near_time'){

                        $("option[data-type='"+obj[k]+"']").attr('selected','true');
                    }
                    if (k=='order_status'){
                        if (obj[k]){
                            $("option[data-type='"+obj[k]+"']").attr('selected','true');
                        }
                    }
                    if (k=='orderid'){
                        if (obj[k]){
                            $("#orderNum").val(obj[k]);
                        }
                    }
                }
            }
        });

    </script>
    <div class="user_content float-right">

        <p class="case_title"><span class="green">全部订单</span></p>
        <div class="case_search">
            <div class="form-inline row">
                <div class="form-group col-md-6">
                    <input type="input" class="form-control" id="orderNum"  placeholder="请输入订单号">
                    <button type="submit" id="searchSingleOrder" class="btn btn-success">搜索</button>
                </div>
                <!-- <div class="col-md-2"></div> -->
                <div class="form-group  col-md-6">
                    <label for="sel1">下单时间：</label>
                    <!-- 下拉框内容待定 -->
                    <select class="form-control" id="sel1">
                        <option value="all" data-type="all">全部</option>
                        <option value="week" data-type="week">近一周</option>
                        <option value="month" data-type="month">近一个月</option>
                        <option value="threeMonth" data-type="threeMonth">近三个月</option>
                    </select>
                    <label for="sel2">订单状态：</label>
                    <select class="form-control" id="sel2">
                        <option value=" ">全部</option>
                        <option value="0" data-type="0">待付款</option>
                        <option value="1" data-type="1">待使用</option>
                        <option value="3" data-type="3">待评价</option>
                        <option value="4" data-type="4">已评价</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="mycase_list">
            <!-- 全部订单 -->
            <table class="table mycase_list_table">
                <thead>
                <tr>
                    <th class="td1">商品</th>
                    <th class="td2">单价</th>
                    <th class="td3">数量</th>
                    <th class="td4">实付款</th>
                    <th class="td8">订单状态</th>
                    <th class="td9">操作</th>
                </tr>
                </thead>
            </table>

            <?php if ($orders) :?>
                <?php foreach ($orders AS $order) :?>
                    <table class="table mycase_list_table">
                        <tbody>
                        <!-- 一条订单-start -->
                        <tr class="tr_id">
                            <td colspan="9"><span><?= $order->add_time; ?></span>订单号：<?= $order->orderid; ?></td>
                        </tr>
                        <?php foreach ($order->goods AS $good) :?>
                        <tr>
                            <td class="td1">
                                <a href="<?= UrlService::build(['intergral-goods/detail', 'id' => $good->goods_id]); ?>" class="media">
                                    <img src="<?= $good->goods_pic; ?>" class="align-self-center" style="width:80px">
                                    <div class="media-body mt-1">
                                        <h4><?= $good->goods_name; ?></h4>
                                        <p><?= $good->attr; ?></p>
                                    </div>
                                </a>
                            </td>
                            <td class="td2"><span><?= intval($good->goods_price); ?></span>积分</td>
                            <td class="td3">× 1</td>
                            <td class="td4"><span><?= intval($good->goods_pay_price); ?></span>积分</td>

                            <td class="td8" rowspan="2">
                                <p class="p_lg"><?= $order->orderState; ?></p>
                                <a href="<?=UrlService::build(['personal/integral-order-detail', 'number' => $order->orderid]); ?>" class="detail">订单详情</a>
                                <?php if (!in_array($order->order_state, [IntergralOrder::STATUS_WAIT_SEND, IntergralOrder::STATUS_WAIT_PAY,IntergralOrder::STATUS_CLOSE])) :?>
                                <a style="display: none" href="<?=UrlService::build(['personal/integral-order-logistics', 'number' => $order->orderid])?>" class="detail">物流详情</a>
                                <?php endif; ?>
                            </td>
                            <td class="td9" rowspan="2">
                                <?php if ($order->order_state==IntergralOrder::STATUS_WAIT_RECIVE):?>
                                    <a href="javascript:void(0)" class="a a_color a_sure" data-toggle="modal"
                                       data-target="#myModalSure" data-id="confirm" data-val="<?= $order->orderid; ?>">确认收货</a>
                                <?php elseif ($order->order_state==IntergralOrder::STATUS_WAIT_PAY):?>
                                    <a href="javascript:void(0)" class="a a_color a_sure" data-toggle="modal"
                                       data-target="#myModalCancel" data-id="cancel" data-orderid="<?= $order->orderid; ?>">取消订单</a>
                                <?php elseif ($order->order_state==IntergralOrder::STATUS_WAIT_JUDGE):?>
                                    <a href="<?=UrlService::build(['personal/order-comment','orderId'=>$order->orderid])?>" class="a a_assess">立即评价</a>
                                <?php endif;?>

                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <!-- 一条订单-end -->
                        </tbody>
                    </table>
                <?php endforeach; ?>
            <?php else :?>
            <div class="com_nodata">
                <img src="/public/index/images/img_result_nodata.png" alt="订单支付成功" class="img">
                <div class="con">
                    <p class="p1">亲，您最近没有下过订单哦~</p>
                    <a href="<?= UrlService::build('integral/index'); ?>" class="btn btn-warning">去首页逛逛</a>
                </div>
            </div>
            <?php endif; ?>
            <!-- 等待付款 -->
            <!-- 添加table_line后，边框是粉色 -->

            <?=$pageHtml; ?>

        </div>
    </div>

</div>


<!-- 模态框-确认收货 -->
<div class="modal fade" id="myModalSure" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body pt-5 mt-3 mb-5 pb-4">
                是否确认收货？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-warning" data-dismiss="modal" data-toggle="modal"
                        data-target="#myModalSuc" data-id="sendGoods">确定
                </button>
            </div>
        </div>
    </div>
</div>

<!-- 模态框-确认取消 -->
<div class="modal fade" id="myModalCancel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="height: 292px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body pt-5 mt-3 mb-5 pb-4">
                是否确认取消预定？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-warning" data-id="cancelButton">确定</button>
            </div>
        </div>
    </div>
</div>


<?php include APP_PATH . '/views/common/footer.php'; ?>
<script>

    //点击取消订单
    $("[data-id=\"cancel\"]").on('click',function () {
        $('[data-id="cancelButton"]').attr('data-val', $(this).attr('data-orderid'));
        autoDomHeight($("#myModalCancel"));
    });

    //取消订单
    $("[data-id=\"cancelButton\"]").on('click',function () {

        var orderid = $(this).attr('data-val');

        var url="<?=UrlService::build(['personal/integral-order-cancel'])?>";
        $.get(url, {number : orderid}, function (res) {
                alert(res.msg);
        },'json');
        $("#myModalCancel").modal('hide');
    });

   $(document).on('click','#globalAlterShadow .btn-warning',function () {
       window.location.reload();
   });

    $('[data-id="confirm"]').click(function() {
       $('[data-id="sendGoods"]').attr('data-val', $(this).attr('data-val'));
    });

    $('[data-id="sendGoods"]').click(function () {
        var number = $(this).attr('data-val');
        $.get('<?= UrlService::build(['personal/received-intergral']); ?>', {number : number}, function (res) {
            res = JSON.parse(res);
            if (res.status) {
                alert("确认收货成功", function () {
                    window.location.reload();
                });
                return false;
            }
            alert(res.msg);
        })
    });

    //点击搜索
    $("#searchSingleOrder").on('click',function () {
        var orderNum=$("#orderNum").val();

        window.location.href = rebuildQueryString("<?=UrlService::build(['personal/integral-order'])?>", {orderid : orderNum});
    });
    //下拉搜索
    $("#sel1").on('change',function () {
        var near_time=$(this).val();
        window.location.href= rebuildQueryString("<?=UrlService::build(['personal/integral-order'])?>", {near_time : near_time});
    });
    $("#sel2").on('change',function () {
        var order_status=$(this).val();
        window.location.href= rebuildQueryString("<?=UrlService::build(['personal/integral-order'])?>", {order_status : order_status});
    })
</script>

application/index/views/personal/my-account-pass.php
<?php

use DL\service\UrlService;
use common\models\FloorIndex;
use common\models\Ticket;
use yii\bootstrap\ActiveForm;

include APP_PATH . '/views/common/header.php'; ?>

<?php include APP_PATH . '/views/common/guider.php'; ?>


    <div class="mx-auto w1200 clearfix pb-5 mt-3">
        <?php include __DIR__ . '/common/left-column.php' ?>
        <div class="user_content float-right">
            <p class="case_title"><span class="green">修改密码</span></p>

            <div class="myaccount">

                <div class="account_pass">
                    <ul>
                        <li><label for="">原密码：</label><input type="password" name="oldPwd" autocomplete="off"
                                                             class="account_input"></li>
                        <li><label for="">新密码：</label><input type="password" name="newPwd" autocomplete="off"
                                                             class="account_input"></li>
                        <li><label for="">确认新密码：</label><input type="password" name="newPwdTwo" autocomplete="off"
                                                               class="account_input"></li>
                        <a href="javascript:void(0)" class="btn btn-success account_btn">提交修改</a>
                    </ul>
                </div>

            </div>

        </div>

    </div>

    <script>

        //点击提交
        $(".account_btn").on('click', function () {
            var oldPwd = $("input[name='oldPwd']").val(),
                newPwd = $("input[name='newPwd']").val(),
                newPwdTwo = $("input[name='newPwdTwo']").val();
            $.ajax({
                type: "POST", // 数据提交类型
                url: "<?=UrlService::build(['personal/my-account-pass'])?>", // 发送地址
                data: {"oldPwd": oldPwd, "newPwd": newPwd, "newPwdTwo": newPwdTwo}, //发送数据
                async: true, // 是否异步
                dataType: 'json',
                success: function (re) {
                    if (re.code == 1) {
                        alert("修改密码成功");
                        window.location.href = "<?=UrlService::build(['personal/my-account'])?>"
                    } else {
                        alert("修改密码失败")
                    }
                },
                error: function () {
                    alert("异常")
                },
            });


        })

    </script>


<?php include APP_PATH . '/views/common/footer.php'; ?>